# Generated by Django 4.2.4 on 2023-08-15 11:53

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_options_alter_user_managers_user_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to=user.models.user_image_file_path
            ),
        ),
    ]
