# Generated by Django 4.2.4 on 2023-08-17 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                default=0, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
